server:
  port: 8083
  servlet:
    context-path: /genshin
spring:
  application:
    name: genshin
  profiles:
    active: dev
  config:
    import: classpath:es-${spring.profiles.active:dev}.yml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: life-tools
    stream:
      bindings:
        hero-out-0:
          destination: hero-topic
          content-type: application/json
          group: genshin-impact
          binder: rocketmq
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
          group: genshin-impact
        bindings:
          hero-out-0:
            producer:
              group: genshin-impact
              send_msg_timeout: 10000

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.loafer.genshin.model
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
feign:
  sentinel:
    enabled: true
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.loafer.genshin.controller
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    sql: debug
    org.springframework.cloud.stream: DEBUG