server:
  port: 8080
  servlet:
    context-path: /
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: life-tools
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true
            maxAge: 1800
      routes:
        - id: lottery-route
          uri: lb://lottery-service
          predicates:
            - Path=/api/lottery/**
          filters:
            - StripPrefix=1
        - id: oss-route
          uri: lb://oss-service
          predicates:
            - Path=/api/oss/**
          filters:
            - StripPrefix=1
        - id: genshin-route
          uri: lb://genshin-service
          predicates:
            - Path=/api/genshin/**
          filters:
            - StripPrefix=1

knife4j:
  gateway:
    enabled: true
    strategy: discover # discover：服务发现（自动聚合），MANUAL：手动配置路由
    discover:
      version: openapi3
      enabled: true
      excluded-services:
        # 排除order开头的配置
        - gateway.*
#    routes:
#      # openapi3
#      - name: lottery-route
#        service-name: lottery-service
#        url: /api/lottery/v3/api-docs
#        #context-path: /lottery
#        order: 1
#      - name: oss-route
#        service-name: oss-service
#        url: /api/oss/v3/api-docs
#        #context-path: /oss
#        order: 0