server:
  port: 8082
  servlet:
    context-path: /lottery
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: cba3d3fa-ab76-4ae7-a9b9-e7ac16efc865
      config:
        server-addr: 127.0.0.1:8848
        namespace: cba3d3fa-ab76-4ae7-a9b9-e7ac16efc865
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/lottery2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.loafer.lottery.model
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

feign:
  sentinel:
    enabled: true

logging:
  level:
    sql: debug