server:
  port: 8082
  servlet:
    context-path: /lottery
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: cba3d3fa-ab76-4ae7-a9b9-e7ac16efc865
      config:
        server-addr: 127.0.0.1:8848
        namespace: cba3d3fa-ab76-4ae7-a9b9-e7ac16efc865
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/lottery2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
mybatis:
  type-aliases-package: com.loafer.lottery.model
  mapper-locations: classpath:mapper/*.xml


feign:
  sentinel:
    enabled: true

logging:
  level:
    sql: debug