server:
  port: 8081
  servlet:
    context-path: /oss
spring:
  profiles:
    active: test
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: life-tools

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.loafer.oss.controller
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

#oss配置
oss:
  endpointInterNet: endpoint（外网）
  endpoint: endpoint
  bucketName: bucketName
  accessKeyId: accessKeyId
  secretAccessKey: secretAccessKey