server:
  port: 8081
  servlet:
    context-path: /oss
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: cba3d3fa-ab76-4ae7-a9b9-e7ac16efc865
      config:
        server-addr: 127.0.0.1:8848
        namespace: cba3d3fa-ab76-4ae7-a9b9-e7ac16efc865
        username: nacos
        password: nacos

#oss配置
oss:
  endpointInterNet: endpoint（外网）
  endpoint: endpoint
  bucketName: bucketName
  accessKeyId: accessKeyId
  secretAccessKey: secretAccessKey